-- 为 GasCache 表添加中文注释
ALTER TABLE GasCache
  MODIFY COLUMN id INT AUTO_INCREMENT COMMENT '主键',
  MODIFY COLUMN address VARCHAR(191) NOT NULL COMMENT '钱包地址',
  MODIFY COLUMN dateStr VARCHAR(191) NOT NULL COMMENT '日期字符串，格式 YYYY-MM-DD',
  MODIFY COLUMN txCount INT NOT NULL COMMENT '交易笔数',
  MODIFY COLUMN feeUsdt VARCHAR(191) NOT NULL COMMENT 'USDT费用',
  MODIFY COLUMN feeRmb VARCHAR(191) NOT NULL COMMENT '人民币费用',
  MODIFY COLUMN updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间';

-- 为表本身添加注释
ALTER TABLE GasCache COMMENT '缓存 Solana 钱包每日的手续费数据';